# Generated by Django 5.0.4 on 2024-05-04 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SCD2Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tech_valid_from", models.DateTimeField(auto_now_add=True)),
                ("tech_valid_to", models.DateTimeField(blank=True, null=True)),
                ("tech_active_flag", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="UMLModel",
            fields=[
                (
                    "scd2model_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="umli_app.scd2model",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="uploads/models/%Y/%m/%d/")),
                ("file_data", models.TextField(blank=True, null=True)),
            ],
            bases=("umli_app.scd2model",),
        ),
        migrations.CreateModel(
            name="UMLModelMetadata",
            fields=[
                (
                    "scd2model_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="umli_app.scd2model",
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                (
                    "model",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="umli_app.umlmodel",
                    ),
                ),
            ],
            bases=("umli_app.scd2model",),
        ),
    ]
