# Generated by Django 5.0.4 on 2024-05-05 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UMLModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tech_valid_from", models.DateTimeField(auto_now_add=True)),
                ("tech_valid_to", models.DateTimeField(blank=True, null=True)),
                ("tech_active_flag", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "source_file",
                    models.FileField(
                        blank=True, null=True, upload_to="models/%Y/%m/%d/"
                    ),
                ),
                ("formatted_data", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UMLModelMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tech_valid_from", models.DateTimeField(auto_now_add=True)),
                ("tech_valid_to", models.DateTimeField(blank=True, null=True)),
                ("tech_active_flag", models.BooleanField(default=True)),
                ("data", models.JSONField(default=dict)),
                (
                    "model",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="umli_app.umlmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
