# Generated by Django 5.0.4 on 2024-05-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("umli_app", "0002_alter_umlmodelmetadata_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="umlmodel",
            name="file_data",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="umlmodel",
            name="tech_valid_to",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="umlmodelmetadata",
            name="tech_valid_to",
            field=models.DateTimeField(null=True),
        ),
    ]
