# Generated by Django 5.0.4 on 2024-05-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("umli_app", "0003_alter_umlmodel_file_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="umlmodel",
            name="file_data",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="umlmodel",
            name="tech_valid_to",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="umlmodelmetadata",
            name="tech_valid_to",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
