# Generated by Django 5.0.4 on 2024-05-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("umli_app", "0004_alter_umlmodel_file_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="umlmodel",
            name="file",
            field=models.FileField(upload_to="uploads/models/%Y/%m/%d/"),
        ),
    ]
