# Generated by Django 5.0.8 on 2024-09-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("umlars_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="umlfile",
            name="last_process_id",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
